# ???????? ????????? ??????????
telegrambots:
  enabled: false

server:
  port: 8080

# ????????? ???????????
logging:
  level:
    com.example: DEBUG
  pattern:
    console: '%d{"yyyy/MM/dd HH:mm:ss,SSS"} [%p] - %msg%n'

# ????????? Telegram ????
com:
  example:
    token: "7640347117:AAE5yfNnc4bs6J5Jd8Hp2XX5QwAU_6ObqmM"
    username: "EarnStars_StarBot"

# ????????? PostgreSQL
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/starbot"
    username: "postgres"
    password: "1234567890"

  # ????????? Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"

  # ????????? Flyway
  flyway:
    enabled: true
    locations: "classpath:com/example/migration"
    baseline-on-migrate: true

# ????????? ??????
reward:
  daily:
    limit: 100
  referral:
    bonus: 1
  minStars:
    minStarsForReward: 20

    spring:
      application:
        name=star-bot: